Update spec to v1.2.171
Needed to give external types the type void.

The error was:

    File "lib/Vk__Types__Screen_surface_create_info_qnx.mli", line 14, characters 17-31:
    14 |   val context : (screen_context Ctypes.ptr, t) Ctypes.field
                          ^^^^^^^^^^^^^^
    Error: Unbound type constructor screen_context